### ISSUE TITLE
Impossible to launch a network game when adding a new heightmap data to heightmap node

### ISSUE THREAD

**Issue by Mikerhinos** [Zylann/godot_heightmap_module#19]
I have a test scene with network managing (based on some demos code because I'm trying to learn :)), scene loading is working fine using a MeshInstance of an .obj , but if I replace it with a heightmap node, it won't load anymore if I add a new heightmap data to it, with this error : 

 drivers/unix/stream_peer_tcp_posix.cpp:275 - Server disconnected!

**Comment by Zylann** [comment]
Do you have an example project? I don't understand what exactly happens here

**Comment by Mikerhinos** [comment]
Sorry my english is pretty bad sometimes lol.
I just pushed to https://bitbucket.org/MikerhinosFR/unnamedgame/src I know there must be a lot of bad things that I should not do but I'm learning :)

**Comment by Zylann** [comment]
I don't have access to this, looks like it's a private repo

**Comment by Mikerhinos** [comment]
Damn sorry lol, new to Bitbucket too :D

**Comment by Zylann** [comment]
Looks like it's another occurence of this: https://github.com/Zylann/godot_heightmap_module/issues/6
Always save HeightMapData as a .heightmap resource, any other saving system won't work.

**Comment by Mikerhinos** [comment]
You're right, saving the heightmap data as a .heightmap file did the trick, thanks ! :)
